### ISSUE TITLE
A small error in the example.

### ISSUE THREAD

**Issue by sxm13** [iRASPA/raspa3#10]
### For the LJ parameter of N2 in the force_field.json, 

{
      "name" : "N_n2",
      "type" : "lennard-jones",    
      "parameters" : [38.298, 3.306],
      "source" : "A. Martin-Calvo et al. , Phys. Chem. Chem. Phys. 2011, 13, 11165-11174"
    },
    {
      "name" : "**_N_n2_**",
      "type" : "none",    
      "parameters" : [0.0, 1.0],
      "source" : "A. Martin-Calvo et al. , Phys. Chem. Chem. Phys. 2011, 13, 11165-11174"
    }
    
    
   ### maybe should change to 

  {
      "name" : "N_n2",
      "type" : "lennard-jones",    
      "parameters" : [38.298, 3.306],
      "source" : "A. Martin-Calvo et al. , Phys. Chem. Chem. Phys. 2011, 13, 11165-11174"
    },
    {
      "name" : "**_N_com_**",
      "type" : "none",    
      "parameters" : [0.0, 1.0],
      "source" : "A. Martin-Calvo et al. , Phys. Chem. Chem. Phys. 2011, 13, 11165-11174"
    }

**Comment by dubbelda** [comment]
Thanks, fixed!
