### ISSUE TITLE
Does RASPA3 supports flexible framework calculations now? And how to run raspa with mpirun -np?

### ISSUE THREAD

**Issue by ZhuochenYu** [iRASPA/RASPA3#14]
Dear Professor, dear Developers,

I have conducted preliminary test calculations using RASPA3 and found it to be 2-3 times more efficient than RASPA2. Could you please let me know if RASPA3 can be further used for parallel calculations with mpirun? Additionally, does RASPA3 currently support reading framework.def for Hybrid MC/MD and osmotic ensemble simulations?

Thank you very much for your assistance.

**Comment by dubbelda** [comment]
No, there is no mpi-support. Also, flexible frameworks, and also flexible molecules are not yet supported. We are currently in the alpha-stage of development trying to get the basic things to work.
