### ISSUE TITLE
Install into M2 Mac

### ISSUE THREAD

**Issue by kenjimochida** [iRASPA/RASPA3#15]
Hi developers,

I had some difficulties installing RASPA3 on my M2 Mac.
But finally, I was succeeded with the following command.
The additional installment of hdf5 and the setting of the environmental variable was required.

brew install llvm ninja cmake doxygen graphviz lapack pybind11 hdf5 
export PATH=/opt/homebrew/opt/llvm/bin:$PATH; 
cmake -B build —preset macos-apple-silicon
ninja -C build 
ninja -C build install
 ctest --test-dir build/tests/raspakit-tests --verbose

**Comment by dubbelda** [comment]
Yes, hdf5 is now needed. Note that we are in the alpha-stage of development.
