### ISSUE TITLE
Density Grid Cube File Anomaly + Feature Clarification Request

### ISSUE THREAD

**Issue by OliMarc** [iRASPA/RASPA3#17]
Hello RASPA3 Developers!

I have been testing the latest version of RASPA3 (version 3.0.0) and its associated grid features. I appreciate the switch from .vtk to .cube files for visualizing the data, as well as the significant speed increase compared to RASPA2. However, I believe there is an issue with how the structure is being written along with the volumetric data. The attached image (Image 1) show the contents of the density grid files generated for my simulation involving the CALF-20 framework.

### Image 1
<img src="https://github.com/user-attachments/assets/b145ad83-e242-43d0-bcd1-8fc48ea380a1" alt="image" width="1000"/>

# Issue:

As shown, the volumetric data appears disproportionately small compared to the structure, and the structure itself has overlapping atoms. When I removed the negative sign in front of the volumetric grid lines [128, 128, 128] in the cube file, the volumetric data then correctly fits into the structure’s cell (as seen in Image 2). However, the atomic positions within the structure remain misaligned and overlapping.

Below is a section from the cube file (grid_calf-20_component_CO2.s0.cube):

```
44 0 0 0
# Volumetric specifications
-128 0.0696390625 0 0                                                  <- 128
-128 4.637153807630808e-18 0.07573046875 0                             <- 128
-128 -0.03235710117321552 6.518043356727116e-18 0.06665162200994751    <- 128
# Structure specifications
30 0.68714 -0.24129790834544715 0.5594118850000003 3.7264335331487968
30 0.687147 7.084243433259654 5.406161885 0.5392702754878441
...
```

### Image 2
<img src="https://github.com/user-attachments/assets/980a052d-aad1-4ce4-aef0-f0e3b5c2a8fe" alt="image" width="1000"/>

# Questions:

In the RASPA3 manual, there is a grid option called "DensityGridPseudoAtomsList", which allows users to specify a list of pseudo atoms. A similar option existed in RASPA2 called "GridTypes". I have tested this option using both your provided examples and my own examples, but it does not seem to alter the density grid outputs. In contrast, RASPA2 would generate the density plot for the guest molecule as well as its center of mass.

1. Is the "DensityGridPseudoAtomsList" feature fully integrated into RASPA3?
2. Should we expect the "DensityGridPseudoAtomsList" to generate the same outputs as "GridTypes" (i.e., center of mass and molecule)?
3. Alternatively, will the new "DensityGridPseudoAtomsList" generate individual cube files for each site specified in the list? For example, will C_co2 have its own cube file, and O_co2 have its own separate cube file?

I have also attached my input and output from my example for your reference.
[13_mc_absorption_of_co2_in_calf-20.zip](https://github.com/user-attachments/files/16680442/13_mc_absorption_of_co2_in_calf-20.zip)

Thank you for your time and attention to these issues.

**Comment by dubbelda** [comment]
On macOS, the output seems okay to me.
![picture](https://github.com/user-attachments/assets/decdb9ad-97c8-4635-bee7-86971e159b19)

What version of iRASPA are you using?

1) No, work in progress. Idea is to make grids for specific atom-types. By default the center of mass of the molecules is used.
2) Yes, but then a density grid of only these pseudo-atom types
3) Yes.

**Comment by OliMarc** [comment]
Thank you for your fast response.

I see, I was using VESTA to visualize the cube instead, thinking the Gaussian cube-formatted file would be readable with any compatible visualization tool. My mistake, thank you!

**Comment by dubbelda** [comment]
Not many tools can handle cube-file that are not cubic (cell angles different from 90 degrees).

Btw. Note that RASPA3 is alpha software. We are working toward the release, but there could be bugs in the code.
