### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by mampaiva** [iRASPA/RASPA3#18]
Using Ubuntu 24.04 when I try to run any functional input in the previous version or example contained in the program folder itself I get the core dumped error "**Illegal instruction (core dumped)**". 

When I try to compile the source code from scratch using instructions,  I get the error: "CMake Error at /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message): Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS CXX) (found version "") Call Stack (most recent call first): /usr/share/cmake-3.28/ "

**Comment by dubbelda** [comment]
I think the illegal instructions comes from the fact that the precompiled binaries are for avx2 cpu's (2013 and newer).
For compilation by source you will need the HDF5-libraries.
