### ISSUE TITLE
Cannot install RASPA3 on ubuntu 22.04

### ISSUE THREAD

**Issue by ZhuochenYu** [iRASPA/raspa3#9]
When running 'make', there is a mistake:
foundationkit/threadpool.ixx:170:42: error: no type named 'jthread' in namespace 'std'; did you mean 'thread'?
  170 |               typename ThreadType = std::jthread>
      |                                     ~~~~~^~~~~~~
      |                                          thread
/usr/lib/llvm-17/bin/../include/c++/v1/__thread/thread.h:161:33: note: 'thread' declared here
  161 | class _LIBCPP_EXPORTED_FROM_ABI thread
      |                                 ^
foundationkit/threadpool.ixx:176:71: error: no member named 'jthread' in namespace 'std'
  176 |         inline static ThreadPool<details::default_function_type, std::jthread>& instance()
      |                                                                  ~~~~~^

**Comment by ZhuochenYu** [comment]
mathkit/ringmatrix.ixx:58:10: error: declaration of 'tuple' must be imported from module 'std_tuple' before it is required
   58 |     std::tuple<RingMatrix, RingMatrix, std::vector<size_t>> HermiteNormalForm();
      |          ^
/usr/lib/llvm-19/bin/../include/c++/v1/tuple:522:28: note: declaration here is not visible
  522 | class _LIBCPP_TEMPLATE_VIS tuple {
      |                            ^
1 error generated.

Another error

**Comment by ZhuochenYu** [comment]
athkit/ring.cpp:99:27: error: implicit instantiation of undefined template 'std::pair<int, int>'
   99 | std::pair<int, int> Ring::divisionModulo(int a, int b)
      |                           ^
/usr/lib/llvm-19/bin/../include/c++/v1/__fwd/pair.h:23:29: note: template is declared here
   23 | struct _LIBCPP_TEMPLATE_VIS pair;
      |                             ^
mathkit/ring.cpp:104:21: error: no member named 'make_pair' in namespace 'std'
  104 |         return std::make_pair(0, 0);
      |                ~~~~~^
mathkit/ring.cpp:107:17: error: no member named 'make_pair' in namespace 'std'
  107 |     return std::make_pair(temp, a - b * temp);

**Comment by dubbelda** [comment]
You need llvm-18 to compile it.
